### ISSUE TITLE
configure: line 4266: syntax error near unexpected token `0.6.7'

### ISSUE THREAD

**Issue by egee-irl** [Kekun/retro-gobject#28]
When running:
`./autogen.sh ` 
On Ubuntu Gnome 15.10, the following error is received:

> checking for valac... /usr/bin/valac
> ./configure: line 4266: syntax error near unexpected token `0.6.7'
> ./configure: line 4266: `GOBJECT_INTROSPECTION_CHECK(0.6.7)'

I have valac version 0.28.1-1

**Comment by Kekun** [comment]
The error message could be more intelligible: you need to install the `gobject-introspection` package.
